### ISSUE TITLE
inputs_embeds are model-specific keyword input, so model needs to be encoder-decoder instead of PhiForCasualLM

### ISSUE THREAD

**Issue by ricperry** [kijai/ComfyUI-moondream#3]
Solution over on vikhyat/moondream in the closed issues section: https://github.com/vikhyat/moondream/issues/50

Original issue was an outdated transformers package. Once updated to the most current transformers package, error was different.

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "ComfyUI/custom_nodes/ComfyUI-moondream/nodes.py", line 81, in process
    answer = self.moondream.answer_question(image_embeds, question, self.tokenizer, max_new_tokens)
  File "ComfyUI/custom_nodes/ComfyUI-moondream/moondream/moondream.py", line 93, in answer_question
    answer = self.generate(
  File "ComfyUI/custom_nodes/ComfyUI-moondream/moondream/moondream.py", line 76, in generate
    output_ids = self.text_model.generate(
  File "ComfyUI/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "ComfyUI/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1220, in generate
    inputs_tensor, model_input_name, model_kwargs = self._prepare_model_inputs(
  File "ComfyUI/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 535, in _prepare_model_inputs
    raise ValueError(
ValueError: If inputs_embeds is passed as model-specific keyword input then model has to be an encoder-decoder and not a PhiForCausalLM.
```

**Comment by ricperry** [comment]
Updated my transformers package to 4.38.2 and now I get this error instead:

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/sab_files/AI_Projects/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/sab_files/AI_Projects/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/sab_files/AI_Projects/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/sab_files/AI_Projects/ComfyUI/custom_nodes/ComfyUI-moondream/nodes.py", line 81, in process
    answer = self.moondream.answer_question(image_embeds, question, self.tokenizer, max_new_tokens)
  File "/sab_files/AI_Projects/ComfyUI/custom_nodes/ComfyUI-moondream/moondream/moondream.py", line 93, in answer_question
    answer = self.generate(
  File "/sab_files/AI_Projects/ComfyUI/custom_nodes/ComfyUI-moondream/moondream/moondream.py", line 76, in generate
    output_ids = self.text_model.generate(
  File "/sab_files/AI_Projects/ComfyUI/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/sab_files/AI_Projects/ComfyUI/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 1544, in generate
    return self.greedy_search(
  File "/sab_files/AI_Projects/ComfyUI/venv/lib/python3.10/site-packages/transformers/generation/utils.py", line 2404, in greedy_search
    outputs = self(
  File "/sab_files/AI_Projects/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/sab_files/AI_Projects/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sab_files/AI_Projects/ComfyUI/custom_nodes/ComfyUI-moondream/moondream/modeling_phi.py", line 709, in forward
    hidden_states = self.transformer(
  File "/sab_files/AI_Projects/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/sab_files/AI_Projects/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sab_files/AI_Projects/ComfyUI/custom_nodes/ComfyUI-moondream/moondream/modeling_phi.py", line 675, in forward
    else func(*args)
  File "/sab_files/AI_Projects/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/sab_files/AI_Projects/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sab_files/AI_Projects/ComfyUI/custom_nodes/ComfyUI-moondream/moondream/modeling_phi.py", line 541, in forward
    attn_outputs = self.mixer(
  File "/sab_files/AI_Projects/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/sab_files/AI_Projects/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sab_files/AI_Projects/ComfyUI/custom_nodes/ComfyUI-moondream/moondream/modeling_phi.py", line 514, in forward
    attn_output_function(x, past_key_values, attention_mask)
  File "/sab_files/AI_Projects/ComfyUI/custom_nodes/ComfyUI-moondream/moondream/modeling_phi.py", line 494, in _forward_cross_attn
    return attn_func(
  File "/sab_files/AI_Projects/ComfyUI/custom_nodes/ComfyUI-moondream/moondream/modeling_phi.py", line 491, in <lambda>
    else lambda fn, *args, **kwargs: fn(*args, **kwargs)
  File "/sab_files/AI_Projects/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/sab_files/AI_Projects/ComfyUI/venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1536, in _call_impl
    return forward_call(*args, **kwargs)
  File "/sab_files/AI_Projects/ComfyUI/venv/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/sab_files/AI_Projects/ComfyUI/venv/lib/python3.10/site-packages/torch/amp/autocast_mode.py", line 16, in decorate_autocast
    return func(*args, **kwargs)
  File "/sab_files/AI_Projects/ComfyUI/custom_nodes/ComfyUI-moondream/moondream/modeling_phi.py", line 318, in forward
    padding_mask.masked_fill_(key_padding_mask, 0.0)
RuntimeError: The expanded size of the tensor (771) must match the existing size (772) at non-singleton dimension 1.  Target sizes: [1, 771].  Tensor sizes: [1, 772]

```

**Comment by ricperry** [comment]
Had to edit modeling_phi.py to fix this. I was hoping this fix would have been carried forward.

![image](https://github.com/kijai/ComfyUI-moondream/assets/34995372/81f58e42-cd2a-4b09-9b0b-54207cb91acb)

**Comment by toyxyz** [comment]
> Had to edit modeling_phi.py to fix this. I was hoping this fix would have been carried forward.
> 
> ![image](https://private-user-images.githubusercontent.com/34995372/310304331-81f58e42-cd2a-4b09-9b0b-54207cb91acb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3OTQzOTQsIm5iZiI6MTcwOTc5NDA5NCwicGF0aCI6Ii8zNDk5NTM3Mi8zMTAzMDQzMzEtODFmNThlNDItY2QyYS00YjA5LTliMGItNTQyMDdjYjkxYWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA3VDA2NDgxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMwODYwOGZjNzk2MWVkMjI0MTFkMmJmZDZjMTg5YjI4MjRhY2RmNzJlNjU5NGYxNzJhZDhhOGU1YWFiZTM4NTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gCQp90S6L8pDOAfuCkzsYFZQat0ZL2bcpIC12AiJWXU)

I was able to resolve the issue this way. Thanks!
